# Generated by Django 4.2.26 on 2025-11-16 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Streaming service',
                'verbose_name_plural': 'Streaming services',
            },
        ),
        migrations.CreateModel(
            name='StreamingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_or_email', models.CharField(max_length=255)),
                ('encrypted_password', models.BinaryField()),
                ('profile_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('never_synced', 'Never synced'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('error', 'Error')], default='never_synced', max_length=20)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('history_dir', models.CharField(blank=True, max_length=255, null=True)),
                ('faiss_dir', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.streamingservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Streaming account',
                'verbose_name_plural': 'Streaming accounts',
                'unique_together': {('user', 'service')},
            },
        ),
    ]
